### ISSUE TITLE
Switch-case no EmailService

### ISSUE THREAD

**Issue by arthurs159** [TaylanTorres09/taxPayer-api#2]
Na parte do emailService, vejo que você fez alguns if's e tenho dois pontos que posso comentar.
![image](https://user-images.githubusercontent.com/77133022/196293592-1c66d58e-c309-4393-a7fa-56f6fb8ba026.png)
Nesta parte, acredito que você possa substituir os if's por swtich case, nesse caso, deixaria o código mais limpo e elegante também deixaria mais fácil de entender e de fácil manutenção, o que acha?

Uma outra coisa, é que quando você faz primeiro o `get` pra depois fazer o `.equals` você abre brecha para gerar um null pointer, pois pode acontecer de você dar get em algo que não exista, saca? Mas isso é só ponto mesmo, fazendo o switch case, estaria tudo certo. : ) Por exemplo:
![image](https://user-images.githubusercontent.com/77133022/196294166-09c57c13-677c-4cee-9ef2-acc8ac859567.png)

**Comment by TaylanTorres09** [comment]
Muito Obrigado irmão pela dica, realmente o código ficou muito mais limpo.

Commit das alterações: 4a5e978 

Resolvi a situação do null Pointer com uma condicional.
Segue na imagem:
![image](https://user-images.githubusercontent.com/53223028/196420242-6d9bb5e4-4bb4-408f-ba49-0937eb2ee34e.png)
